#!/usr/bin/env bash
#
# Boot a generated project and ask it for every page it claims to have.
#
# WHY A COMPILER AND A TYPE CHECKER ARE NOT ENOUGH. `tsc --noEmit` and
# `vitest run` were both green on two configurations that could not serve a
# single page. Neither one exercises Next's React Server Component boundary, and
# that boundary is where the failure lived: `@adminigloo/email/emails` renders
# with React Email, which imports `react-dom/server`, which React resolves —
# under the `react-server` condition every module in the RSC graph is resolved
# with — to a file whose entire body is a throw. One email template reached from
# the invitations router poisoned `src/trpc/server.ts`, and with it every server
# component in the application: `next build` exited 1 and `next dev` answered
# 500 on every route but `/`. The unit tests never noticed, because there is
# nothing about it to notice in a type or in a plan — and a build log is not
# much better, because the same class of fault can compile perfectly and only
# throw when a page is rendered.
#
# So the contract this script adds to CI is the blunt one: a configuration that
# compiles and cannot serve a page must fail. Nothing subtler is needed — the
# regressions this class produces are not off-by-one status codes, they are a
# whole application answering 500. A 3xx passes: with no credentials there is no
# session, and every /admin route redirecting to sign-in is the panel working.
# A 4xx does not, because the route list is read off the pages the build emitted
# and a page the build emitted should not be missing.
#
# THE ROUTE LIST IS READ OFF THE PROJECT, never written down here. A hardcoded
# list is a list that silently stops covering the pages an overlay added, and
# the matrix exists precisely to run combinations nobody generated by hand. Every
# `app/**/page.tsx` becomes a URL, route groups are dropped because the router
# drops them, and dynamic segments are skipped: `/products/[slug]` needs a slug
# that exists in a database this project has never been given, and a 404 from it
# would be correct. An OPTIONAL catch-all is not skipped — `[[...sign-in]]`
# matches zero segments, so `/sign-in` is a real URL with no argument to invent,
# and it is one of the pages the regression took down.
#
# Invoked as `bash <path>` rather than executed directly, for the same reason as
# report-matrix-failure.sh: this repository is developed on Windows, where git
# cannot record the executable bit.
#
# usage: route-sweep.sh <app-dir> <label> <port> <server command...>

set -uo pipefail

app="${1:?app directory}"
label="${2:?label, eg 'next start'}"
port="${3:?port}"
shift 3
[ "$#" -gt 0 ] || { echo "no server command given"; exit 2; }

log="$app/route-sweep-$(echo "$label" | tr ' /' '--').log"
base="http://127.0.0.1:${port}"

# Every static page the project emitted, as a URL.
routes=$(
  cd "$app" && find app -name page.tsx |
    sed -e 's#\\#/#g' -e 's#^app##' -e 's#/page\.tsx$##' |
    sed -e 's#/([^)]*)##g' |
    sed -e 's#/\[\[\.\.\.[^]]*\]\]##g' |
    grep -v '\[' |
    sed -e 's#^$#/#' |
    sort -u
)

count=$(printf '%s\n' "$routes" | grep -c '^/')
# A scan that finds nothing passes for ever. Every configuration this scaffold
# can generate has at least `/`, `/setup` and `/setup/email` or `/members`.
if [ "$count" -lt 3 ]; then
  echo "::error title=route sweep::found only ${count} static routes under ${app}/app — the scan has rotted, or the project emitted almost nothing."
  exit 1
fi

cd "$app" || exit 1
"$@" > "$log" 2>&1 &
server=$!
# Kill the whole group: `next dev` and `next start` both fork workers, and a
# bare kill of the parent leaves them holding the port for the next entry.
trap 'kill "$server" 2>/dev/null; pkill -P "$server" 2>/dev/null; wait "$server" 2>/dev/null' EXIT

# Up to two minutes. A cold `next dev` compiles the root route on the first
# request, and on a loaded runner that is not fast.
ready=""
for _ in $(seq 1 120); do
  if ! kill -0 "$server" 2>/dev/null; then
    echo "::error title=route sweep::${label} exited before it served anything."
    tail -n 40 "$log"
    exit 1
  fi
  if curl -fsS -o /dev/null --max-time 20 "${base}/" 2>/dev/null; then
    ready="yes"
    break
  fi
  sleep 1
done

if [ -z "$ready" ]; then
  echo "::error title=route sweep::${label} never answered on ${base}/."
  tail -n 40 "$log"
  exit 1
fi

echo "----- ${label}: ${count} static routes -----"
failed=""
served=0
for route in $routes; do
  status=$(curl -s -o /dev/null --max-time 60 -w '%{http_code}' "${base}${route}")
  printf '%s %s\n' "$status" "$route"
  case "$status" in
    # A page that rendered.
    200) served=$((served + 1)) ;;
    # A page that decided this caller may not see it. Every /admin route
    # redirects to sign-in on a project with no session, which is the panel
    # working rather than the panel broken.
    30*) ;;
    # Everything else. A 404 on a route the build listed is as wrong as a 500,
    # and 000 is curl saying the server closed the connection.
    *) failed="${failed}${status} ${route}"$'\n' ;;
  esac
done
echo "----- end ${label} -----"

# A build in which every page redirects is a build with an authentication bug,
# and it would satisfy the loop above without rendering a single line of React.
if [ "$served" -lt 3 ]; then
  failed="${failed}only ${served} of ${count} routes rendered; the rest redirected"$'\n'
fi

if [ -n "$failed" ]; then
  echo "::error title=route sweep (${label})::a page the build emitted did not serve"
  {
    echo "## route sweep failed — ${label}"
    echo
    echo '```'
    printf '%s' "$failed"
    echo '```'
    echo
    echo "Server output:"
    echo
    echo '```'
    tail -n 60 "$log"
    echo '```'
  } >> "${GITHUB_STEP_SUMMARY:-/dev/null}"
  printf '%s' "$failed"
  echo "----- ${label} server output -----"
  tail -n 60 "$log"
  exit 1
fi

echo "${label}: ${served} of ${count} static routes rendered, the rest redirected. None failed."
