import Link from "next/link";
import { renderInvitationEmail } from "@/emails/invitation";
import { Card, CardBody, CardHeader, Notice, PageHeader } from "@/components/ui";

/**
 * What the mail this project sends actually looks like.
 *
 * An email template is the one piece of UI in a codebase with no way to see it.
 * It renders inside somebody else's client, on a trigger you have to reproduce,
 * and the usual way to check a change is to invite a colleague and hope. So the
 * loop becomes: edit, deploy, invite, wait, squint — and the predictable result
 * is that nobody edits it, and the invitation mail keeps saying whatever it
 * said on the day it was written.
 *
 * SAMPLE DATA, NEVER REAL DATA. This route reads nothing: no database, no
 * session, no query parameters. That is what makes it safe to leave reachable
 * on a deployment — there is no invitation here to leak and no token to spend,
 * and a preview that took an id from the URL would be exactly such a leak. The
 * sample values are deliberately implausible enough that nobody mistakes this
 * page for a record of something that was sent; the delivery log under
 * `email_events` is where that lives.
 *
 * The HTML renders inside an `iframe` with `srcDoc`, not `dangerouslySetInnerHTML`.
 * An email body is a whole document with its own `<body>` styling, and dropping
 * one into the page would apply the mail's background and font to the app
 * around it — you would be previewing a hybrid of the two. The iframe also
 * matches what a mail client does: a separate document with no access to this
 * page's stylesheet, which is the property that makes the preview honest.
 *
 * `sandbox` with nothing enabled. The body is generated by this project, so
 * there is nothing hostile in it today, and one day somebody will paste a
 * customer's __TENANT_LABEL_LOWER__ name into the sample to reproduce a bug.
 *
 * RENDERED PER REQUEST, exactly like `/setup` beside it, and this line used to
 * read `force-static` — which broke `next build` for every project generated
 * with `--email` the moment Clerk keys were added. The reasoning behind the old
 * value was sound about this file and wrong about where it sits: the page reads
 * nothing, so nothing here needs a request. `app/(site)/layout.tsx` does. The
 * header it mounts reads the Clerk session, a forced-static route renders at
 * BUILD time where no proxy has run, and `auth()` throws there — so this was
 * the only prerendered page in the app and therefore the only one that could
 * fail that way. Nothing else under `(site)` forces static rendering, which is
 * why nothing else did.
 *
 * Nor is static what this page wants. It is a developer surface — the sibling
 * of `/setup`, in the same footer group, deleted alongside it at launch — and
 * its whole value is showing what THIS deployment renders now. Baking it at
 * build time also made it the one route whose output depended on which
 * credentials were present, which is the asymmetry that hid the fault.
 * `force-dynamic` is one behaviour in every configuration.
 */
export const dynamic = "force-dynamic";

const SAMPLE = {
  tenantName: "Northwind Trading",
  invitedBy: "Ada Lovelace",
  roleName: "Admin",
  url: "https://example.com/invite/sample-token-not-a-real-invitation",
  expiresAt: new Date("2026-01-08T09:00:00.000Z"),
  productName: "__PROJECT_NAME__",
} as const;

export default function EmailPreviewPage() {
  const invitation = renderInvitationEmail(SAMPLE);

  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <PageHeader
        title="Email templates"
        description="Every message this project can send, rendered from sample data. Nothing here is read from the database and nothing is sent."
      />

      <Notice tone="info" title="This is not a delivery log">
        What was actually sent — including the messages recorded as{" "}
        <code className="font-mono">skipped</code> because no API key is set — is
        in the <code className="font-mono">email_events</code> table.{" "}
        <Link href="/setup" className="text-accent underline underline-offset-2">
          /setup
        </Link>{" "}
        says whether this deployment can send at all.
      </Notice>

      <Card className="mt-6">
        <CardHeader
          title="Invitation"
          hint="Sent to somebody who has been invited to join."
        />
        <CardBody className="flex flex-col gap-4">
          <div>
            <p className="text-[11px] font-medium uppercase tracking-wider text-ink-muted">
              Subject
            </p>
            <p className="text-sm text-ink">{invitation.subject}</p>
          </div>

          <div>
            <p className="mb-1 text-[11px] font-medium uppercase tracking-wider text-ink-muted">
              HTML
            </p>
            <iframe
              title="Invitation email, HTML version"
              srcDoc={invitation.html}
              sandbox=""
              className="h-[26rem] w-full rounded-[--radius-card] border border-line bg-surface"
            />
          </div>

          <div>
            <p className="mb-1 text-[11px] font-medium uppercase tracking-wider text-ink-muted">
              Plain text
            </p>
            {/* Shown, not hidden behind a toggle. The text part is what a spam
                filter reads and what a watch or a terminal client renders, and
                a preview that only shows the pretty half is how it rots. */}
            <pre className="overflow-x-auto rounded-[--radius-card] border border-line bg-canvas p-3 font-mono text-xs whitespace-pre-wrap text-ink-muted">
              {invitation.text}
            </pre>
          </div>
        </CardBody>
      </Card>
    </main>
  );
}
