import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { DEFAULT_ANSWERS, capabilitiesFor, type Answers } from "../answers.js";
import {
  CAPABILITY_EVIDENCE,
  UNDISTINGUISHED_CAPABILITIES,
  UnprovableCapabilityError,
  assertCapabilitiesAreProvable,
} from "../capabilities.js";
import { planEmit } from "../emit.js";

const TEMPLATE_DIR = join(__dirname, "..", "..", "template");

function answers(overrides: Partial<Answers> = {}): Answers {
  return { ...DEFAULT_ANSWERS, projectName: "acme", ...overrides };
}

/**
 * Every configuration, because the lie this catches is configuration-shaped.
 *
 * `ai.streaming` was claimed only under `--ai`, so it was false in exactly the
 * configuration nobody generated by default and true in none. A table that
 * exercised the defaults would have agreed with it.
 */
const EVERY_CONFIGURATION = ["none", "one-time", "subscription", "both"].flatMap(
  (businessModel) =>
    ["none", "minimal", "full"].flatMap((adminShell) =>
      [true, false].flatMap((includeAi) =>
        [true, false].flatMap((includeEmail) =>
          ["Organization", "none"].map(
            (tenantNoun) =>
              [
                `--model ${businessModel} --admin ${adminShell}` +
                  `${includeAi ? " --ai" : ""}${includeEmail ? " --email" : ""}` +
                  ` --tenant ${tenantNoun}`,
                {
                  businessModel,
                  adminShell,
                  includeAi,
                  includeEmail,
                  tenantNoun,
                },
              ] as const,
          ),
        ),
      ),
    ),
) as readonly (readonly [string, Partial<Answers>])[];

describe("the manifest can prove everything it claims", () => {
  it.each(EVERY_CONFIGURATION)(
    "every claimed capability is provable for %s",
    async (_label, overrides) => {
      // `planEmit` itself calls `assertCapabilitiesAreProvable`, so a violation
      // throws here rather than failing an assertion — which is the point: the
      // generator refuses to write a manifest it cannot back up. The explicit
      // second call is for the message you get when it is the evidence rather
      // than the emit that is wrong.
      const plan = await planEmit(TEMPLATE_DIR, "/out", answers(overrides));
      assertCapabilitiesAreProvable(plan, capabilitiesFor(answers(overrides)));
    },
  );

  it("has a row for every key capabilitiesFor can emit, and no others", async () => {
    // Both directions. A key with no row cannot be claimed at all — that is
    // what `assertCapabilitiesAreProvable` enforces — but a ROW with no key is
    // rot: evidence for a capability that was renamed or removed, quietly
    // proving nothing while looking like coverage.
    const claimable = new Set(
      EVERY_CONFIGURATION.flatMap(([, overrides]) =>
        capabilitiesFor(answers(overrides)),
      ),
    );
    const documented = new Set(CAPABILITY_EVIDENCE.map((row) => row.capability));

    for (const key of claimable) {
      expect(
        documented.has(key),
        `capabilitiesFor can emit "${key}" and CAPABILITY_EVIDENCE has no row ` +
          `for it. Generation will throw rather than write the manifest.`,
      ).toBe(true);
    }
    for (const key of documented) {
      expect(
        claimable.has(key),
        `CAPABILITY_EVIDENCE has a row for "${key}", which no configuration ` +
          `claims. Delete the row, or find out why the key stopped being emitted.`,
      ).toBe(true);
    }
  });

  it("does not prove a capability the project did not claim", async () => {
    // The inverse drift, and the one an evidence table normally misses: the
    // project grew the thing and the manifest never said so. A `--admin none`
    // project that somehow emitted app/admin/page.tsx would pass every other
    // test in this file.
    for (const [label, overrides] of EVERY_CONFIGURATION) {
      const plan = await planEmit(TEMPLATE_DIR, "/out", answers(overrides));
      const claimed = new Set(capabilitiesFor(answers(overrides)));

      for (const row of CAPABILITY_EVIDENCE) {
        if (claimed.has(row.capability)) continue;
        if (
          Object.prototype.hasOwnProperty.call(
            UNDISTINGUISHED_CAPABILITIES,
            row.capability,
          )
        ) {
          continue;
        }
        expect(
          row.provenBy(plan),
          `${label} does not claim "${row.capability}" and the emitted project ` +
            `provides it anyway. Either claim it in capabilitiesFor, or add it ` +
            `to UNDISTINGUISHED_CAPABILITIES with the reason the evidence ` +
            `cannot tell it from a sibling.`,
        ).toBe(false);
      }
    }
  });

  it("keeps the indistinguishable list honest", async () => {
    // The prune mechanism. An exemption is only legitimate while the key really
    // is provable in a configuration that does not claim it; the day the
    // generator emits something structural for one of these, no such
    // configuration exists and this fails, telling you to delete the entry.
    const plans = await Promise.all(
      EVERY_CONFIGURATION.map(async ([, overrides]) => ({
        plan: await planEmit(TEMPLATE_DIR, "/out", answers(overrides)),
        claimed: new Set(capabilitiesFor(answers(overrides))),
      })),
    );

    for (const key of Object.keys(UNDISTINGUISHED_CAPABILITIES)) {
      const row = CAPABILITY_EVIDENCE.find((r) => r.capability === key);
      expect(row, `${key} is excused and has no evidence row`).toBeDefined();
      const stillAmbiguous = plans.some(
        ({ plan, claimed }) => !claimed.has(key) && row?.provenBy(plan) === true,
      );
      expect(
        stillAmbiguous,
        `"${key}" is listed in UNDISTINGUISHED_CAPABILITIES and is no longer ` +
          `indistinguishable: no configuration provides it without claiming ` +
          `it. Remove the entry so the exclusivity check covers it again.`,
      ).toBe(true);
    }
  });

  it("refuses to write a manifest claiming something absent", async () => {
    // The assertion the whole file rests on, exercised directly. Without this
    // the three tests above could all be green against a predicate that
    // returned true unconditionally.
    const plan = await planEmit(TEMPLATE_DIR, "/out", answers());
    expect(() =>
      assertCapabilitiesAreProvable(plan, ["ai.streaming"]),
    ).toThrow(UnprovableCapabilityError);
    expect(() =>
      assertCapabilitiesAreProvable(plan, ["invented.capability"]),
    ).toThrow(/no row in CAPABILITY_EVIDENCE/);
  });

  it("names the emitted file behind every claim", () => {
    // A row whose `why` says nothing is a row nobody can audit. This is the
    // cheapest possible guard against a future entry added as `provenBy: () =>
    // true` with an empty reason to make a build go green.
    for (const row of CAPABILITY_EVIDENCE) {
      expect(row.why.length, `${row.capability} has no stated evidence`)
        .toBeGreaterThan(40);
    }
  });
});

describe("the ai overlay is what makes ai.streaming true", () => {
  it("emits a route that opens a stream, only with --ai", async () => {
    const withAi = await planEmit(TEMPLATE_DIR, "/out", answers({ includeAi: true }));
    const route = withAi.files.get(
      join("app", "api", "ai", "chat", "route.ts"),
    );
    expect(route, "--ai emits no AI route").toBeDefined();
    expect(route).toContain("createStreamRoute(");

    const without = await planEmit(TEMPLATE_DIR, "/out", answers({ includeAi: false }));
    for (const path of without.files.keys()) {
      expect(
        path.split(/[\\/]/).includes("ai") && path.startsWith("app"),
        `${path} is an AI route in a project generated without --ai`,
      ).toBe(false);
    }
  });

  it("rate limits the route per request AND per day, and fails closed", async () => {
    // An unthrottled model route is the one omission that produces a same-day
    // invoice. A per-minute cap alone is not enough — twenty a minute is
    // 28,800 calls a day — so both budgets are named here.
    const plan = await planEmit(TEMPLATE_DIR, "/out", answers({ includeAi: true }));
    const route = plan.files.get(join("app", "api", "ai", "chat", "route.ts")) ?? "";
    expect(route).toContain("RATE_LIMIT_POLICIES.ai");
    expect(route).toContain("RATE_LIMIT_POLICIES.aiDaily");
    // Fail CLOSED. The default limiter fails open, which is right for every
    // other endpoint and wrong for the one that spends money.
    expect(route).toContain("failClosedLimiter");
    expect(route).not.toContain("await limiter.limit");
    expect(route).toContain("status: 429");
  });

  it("boots with no API key, and says so with a real answer", async () => {
    const plan = await planEmit(TEMPLATE_DIR, "/out", answers({ includeAi: true }));
    const route = plan.files.get(join("app", "api", "ai", "chat", "route.ts")) ?? "";
    // A documented no-op with a real return value: 503 and the (empty) list of
    // providers. Never a throw, never a silent early return.
    expect(route).toContain("ai_not_configured");
    expect(route).toContain("status: 503");
    expect(route).toContain("configuredAiProviders(env)");
  });

  it("writes a usage row that something reads", async () => {
    // `ai_usage` existed and nothing wrote to it; then the route wrote to it
    // and nothing read it. Both halves, or the table is the empty error viewer
    // over again.
    const plan = await planEmit(TEMPLATE_DIR, "/out", answers({ includeAi: true }));
    expect(plan.files.get(join("src", "server", "ai.ts"))).toContain(
      "db.insert(aiUsage)",
    );
    expect(plan.files.get(join("src", "server", "routers", "ai.ts"))).toContain(
      "tenantSpendSince",
    );
    expect(plan.files.get(join("src", "server", "routers", "_app.ts"))).toContain(
      "ai: aiRouter",
    );
  });

  it("declares the provider SDK it imports", async () => {
    // The pino lesson: a package imported at the top of an emitted module is a
    // package the manifest has to name, whatever pnpm's auto-install-peers
    // happens to be set to.
    const plan = await planEmit(TEMPLATE_DIR, "/out", answers({ includeAi: true }));
    const pkg = JSON.parse(plan.files.get("package.json") ?? "{}") as {
      dependencies: Record<string, string>;
    };
    expect(pkg.dependencies["@anthropic-ai/sdk"]).toBeDefined();

    const withoutAi = await planEmit(TEMPLATE_DIR, "/out", answers());
    const bare = JSON.parse(withoutAi.files.get("package.json") ?? "{}") as {
      dependencies: Record<string, string>;
    };
    expect(bare.dependencies["@anthropic-ai/sdk"]).toBeUndefined();
  });
});
